name: Ping Google Check Run Example

on: [push]

permissions:
  checks: write
  statuses: write

jobs:
  ping-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Check Run
        id: create_check_run
        run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "Ping Google",
              "head_sha": "${{ github.sha }}",
              "status": "in_progress"
            }')
          check_run_id=$(echo "$response" | jq -r .id)
          echo "Check Run ID: $check_run_id"
          echo "::set-output name=check_run_id::$check_run_id"
