name: Simple Check Run Example

on: [push]

permissions:
  checks: write
  statuses: write

jobs:
  example-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Check Run
        id: create_check_run
        uses: actions/github-script@v6
        with:
          script: |
            const checkRun = await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Simple Check',
              head_sha: context.sha,
              status: 'in_progress',
            });
            return checkRun.data.id;

      - name: Simulate Work
        run: |
          sleep 2
          echo "Task completed successfully!"

      - name: Update Check Run
        uses: actions/github-script@v6
        with:
          script: |
            const conclusion = 'success';
            const checkRunId = '${{ steps.create_check_run.outputs.result }}';

            await github.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: checkRunId,
              conclusion: conclusion,
              output: {
                title: 'Check Result',
                summary: 'The task has been completed successfully.',
              },
            });
